theme = "stephenc.me"
languageCode = "en-us"
baseurl = "http://stephenc.me/"
title = "Stephen Chen"

[params]
  currentyear = "2016"
  resumeurl = "stephenchenresume.pdf"
  githuburl = "https://github.com/SCDevy"
  linkedinurl = "https://www.linkedin.com/in/stephenyhchen"
  mediumurl = "https://medium.com/@scdevy"
  twitterurl = "https://twitter.com/SCDevy"
  soundcloudurl = "https://soundcloud.com/stephenchenmusic"
  instagramurl = "https://www.instagram.com/scdevy/"
